#!/usr/bin/env python3
"""Inventory core C modules, headers, and binding entry points.

This script scans the repository and writes deterministic JSON/Markdown artifacts
that can be used for documentation and tooling.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Iterable


DEFAULT_OUTPUT_JSON = Path("docs/generated/component_inventory.json")
DEFAULT_OUTPUT_MARKDOWN = Path("docs/generated/component_inventory.md")


def _sorted_posix(paths: Iterable[Path], base_dir: Path) -> list[str]:
    return sorted(path.relative_to(base_dir).as_posix() for path in paths)


def collect_inventory(repo_root: Path) -> dict[str, object]:
    core_src_dir = repo_root / "libpolycall-v1" / "src"
    core_include_dir = repo_root / "libpolycall-v1" / "include"

    core_modules = _sorted_posix(core_src_dir.glob("*.c"), repo_root)
    headers = _sorted_posix(core_include_dir.glob("*.h"), repo_root)

    binding_patterns = {
        "python": [
            "bindings/pypolycall/setup.py",
            "bindings/pypolycall/pypolycall/__init__.py",
            "bindings/pypolycall/pypolycall/core.py",
        ],
        "node": [
            "bindings/node-polycall/package.json",
            "bindings/node-polycall/src/index.js",
        ],
        "go": [
            "bindings/go-polycall/go.mod",
            "bindings/go-polycall/pkg/polycall.go",
        ],
        "java": [
            "bindings/java-polycall/pom.xml",
            "bindings/java-polycall/src/main/java/io/polycall/Core.java",
        ],
        "lua": [
            "bindings/lua-polycall/lua-polycall-1.0-1.rockspec",
            "bindings/lua-polycall/polycall/init.lua",
        ],
    }

    bindings: dict[str, list[str]] = {}
    for language in sorted(binding_patterns):
        existing = []
        for pattern in binding_patterns[language]:
            path = repo_root / pattern
            if path.exists():
                existing.append(path.relative_to(repo_root).as_posix())
        bindings[language] = sorted(existing)

    inventory = {
        "repo_root": repo_root.name,
        "core_modules": core_modules,
        "headers": headers,
        "binding_entry_points": bindings,
        "counts": {
            "core_modules": len(core_modules),
            "headers": len(headers),
            "binding_entry_points": sum(len(items) for items in bindings.values()),
        },
    }
    return inventory


def render_markdown(inventory: dict[str, object]) -> str:
    core_modules = inventory["core_modules"]
    headers = inventory["headers"]
    bindings = inventory["binding_entry_points"]
    counts = inventory["counts"]

    lines = [
        "# Component Inventory",
        "",
        "_Generated by `tools/scripts/analyze_components.py`._",
        "",
        "## Summary",
        "",
        f"- Core C modules: {counts['core_modules']}",
        f"- Headers: {counts['headers']}",
        f"- Binding entry points: {counts['binding_entry_points']}",
        "",
        "## Core C Modules",
        "",
    ]

    for module in core_modules:
        lines.append(f"- `{module}`")

    lines.extend(["", "## Headers", ""])
    for header in headers:
        lines.append(f"- `{header}`")

    lines.extend(["", "## Binding Entry Points", ""])
    for language in sorted(bindings):
        lines.append(f"### {language.capitalize()}")
        entries = bindings[language]
        if entries:
            lines.extend(f"- `{entry}`" for entry in entries)
        else:
            lines.append("- _(none detected)_")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def write_inventory(repo_root: Path, output_json: Path, output_markdown: Path) -> dict[str, object]:
    inventory = collect_inventory(repo_root)

    output_json.parent.mkdir(parents=True, exist_ok=True)
    output_markdown.parent.mkdir(parents=True, exist_ok=True)

    output_json.write_text(json.dumps(inventory, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    output_markdown.write_text(render_markdown(inventory), encoding="utf-8")

    return inventory


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Analyze core components and binding entry points")
    parser.add_argument("--repo-root", type=Path, default=Path("."), help="Repository root")
    parser.add_argument("--output-json", type=Path, default=DEFAULT_OUTPUT_JSON, help="Path for JSON artifact")
    parser.add_argument(
        "--output-markdown",
        type=Path,
        default=DEFAULT_OUTPUT_MARKDOWN,
        help="Path for markdown artifact",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    repo_root = args.repo_root.resolve()
    write_inventory(repo_root, args.output_json, args.output_markdown)


if __name__ == "__main__":
    main()
