#!/usr/bin/env python3
"""Generate a deterministic docs index for traversal workflows."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


DEFAULT_OUTPUT_MARKDOWN = Path("docs/generated/docs_index.md")
DEFAULT_OUTPUT_JSON = Path("docs/generated/docs_index.json")


def _load_decision_states(repo_root: Path) -> dict[str, object]:
    fixture_path = repo_root / "tests" / "fixtures" / "decision_states.json"
    if not fixture_path.exists():
        return {"fixture_path": fixture_path.as_posix(), "states": []}

    payload = json.loads(fixture_path.read_text(encoding="utf-8"))
    states = payload.get("states", [])
    return {
        "fixture_path": fixture_path.relative_to(repo_root).as_posix(),
        "states": sorted(states, key=lambda item: (item.get("status", ""), item.get("id", ""))),
    }


def collect_docs(repo_root: Path) -> list[str]:
    docs_dir = repo_root / "docs"
    docs_files = sorted(
        path.relative_to(repo_root).as_posix()
        for path in docs_dir.rglob("*.md")
        if "generated" not in path.parts
    )
    return docs_files


def build_index(repo_root: Path) -> dict[str, object]:
    docs_files = collect_docs(repo_root)
    decision_data = _load_decision_states(repo_root)
    states = decision_data["states"]

    grouped_states: dict[str, list[dict[str, object]]] = {}
    for state in states:
        grouped_states.setdefault(state.get("status", "unknown"), []).append(state)

    for key in list(grouped_states.keys()):
        grouped_states[key] = sorted(grouped_states[key], key=lambda item: item.get("id", ""))

    return {
        "repo_root": repo_root.name,
        "docs": docs_files,
        "decision_fixture": decision_data["fixture_path"],
        "decision_states_by_status": dict(sorted(grouped_states.items())),
        "counts": {
            "docs": len(docs_files),
            "decision_states": len(states),
        },
    }


def render_markdown(index: dict[str, object]) -> str:
    docs_files = index["docs"]
    by_status = index["decision_states_by_status"]

    lines = [
        "# Documentation Index",
        "",
        "_Generated by `tools/scripts/generate_docs_index.py`._",
        "",
        "## Summary",
        "",
        f"- Markdown docs: {index['counts']['docs']}",
        f"- Decision states in fixture: {index['counts']['decision_states']}",
        f"- Fixture source: `{index['decision_fixture']}`",
        "",
        "## Markdown Files",
        "",
    ]

    for doc in docs_files:
        lines.append(f"- `{doc}`")

    lines.extend(["", "## Decision States by Status", ""])
    if not by_status:
        lines.append("- _(no decision states detected)_")
    else:
        for status in sorted(by_status):
            lines.append(f"### {status}")
            for state in by_status[status]:
                title = state.get("title", "(untitled)")
                state_id = state.get("id", "(no-id)")
                lines.append(f"- `{state_id}` — {title}")
            lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def write_index(repo_root: Path, output_markdown: Path, output_json: Path) -> dict[str, object]:
    index = build_index(repo_root)
    output_markdown.parent.mkdir(parents=True, exist_ok=True)
    output_json.parent.mkdir(parents=True, exist_ok=True)

    output_markdown.write_text(render_markdown(index), encoding="utf-8")
    output_json.write_text(json.dumps(index, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return index


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate docs traversal index")
    parser.add_argument("--repo-root", type=Path, default=Path("."), help="Repository root")
    parser.add_argument("--output-markdown", type=Path, default=DEFAULT_OUTPUT_MARKDOWN, help="Markdown output path")
    parser.add_argument("--output-json", type=Path, default=DEFAULT_OUTPUT_JSON, help="JSON output path")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    write_index(args.repo_root.resolve(), args.output_markdown, args.output_json)


if __name__ == "__main__":
    main()
