#!/usr/bin/env python3
"""Render repo mapping artifacts into markdown for docs/REFERENCE.md."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]


def format_row(record: dict[str, object]) -> str:
    symbols = ", ".join(record.get("symbols", [])) or "-"
    deps = ", ".join(record.get("dependencies", [])) or "-"
    return f"| `{record['file']}` | {symbols} | {deps} |"


def build_section(title: str, records: list[dict[str, object]]) -> list[str]:
    lines = [f"## {title}", "", "| File | Symbols | Dependency hints |", "| --- | --- | --- |"]
    lines.extend(format_row(record) for record in records)
    lines.append("")
    return lines


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--artifact",
        default=ROOT / "tools" / "scripts" / "v1-analysis" / "artifacts" / "repo-map.json",
        type=Path,
        help="Path to repo-map.json artifact.",
    )
    parser.add_argument(
        "--out",
        default=ROOT / "docs" / "REFERENCE.md",
        type=Path,
        help="Path to markdown output.",
    )
    args = parser.parse_args()

    records = json.loads(args.artifact.read_text(encoding="utf-8"))
    core_records = [r for r in records if r.get("category") == "core"]
    binding_records = [r for r in records if r.get("category") == "binding-entry"]

    lines = [
        "# Static Code Traversal Reference",
        "",
        "This file is generated by `tools/scripts/v1-analysis/render_reference_md.py`.",
        "Run the analysis scripts to regenerate deterministic content.",
        "",
    ]
    lines.extend(build_section("libpolycall-v1 Core Map", core_records))
    lines.extend(build_section("Bindings Entry Points", binding_records))

    args.out.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
