#!/usr/bin/env python3
"""Build docs/REFERENCE_INDEX.md from modular indexers."""

from __future__ import annotations

import argparse
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
SCRIPT_DIR = ROOT / "scripts"
OUTPUT_DOC = ROOT / "docs" / "REFERENCE_INDEX.md"


def run_script(script_path: pathlib.Path) -> str:
    proc = subprocess.run(
        [sys.executable, str(script_path)],
        cwd=str(ROOT),
        check=True,
        capture_output=True,
        text=True,
    )
    return proc.stdout.strip()


def build_document(core_index: str, bindings_index: str) -> str:
    parts = [
        "# Reference Index",
        "",
        "This file is generated by `scripts/build_docs_index.py`. Do not edit manually.",
        "",
        "## Core C",
        "",
        core_index,
        "",
        "## Bindings",
        "",
        bindings_index,
        "",
    ]
    return "\n".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=pathlib.Path,
        default=OUTPUT_DOC,
        help="Output markdown path (default: docs/REFERENCE_INDEX.md)",
    )
    args = parser.parse_args()

    core_index = run_script(SCRIPT_DIR / "index_core_c.py")
    bindings_index = run_script(SCRIPT_DIR / "index_bindings.py")
    document = build_document(core_index, bindings_index)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(document + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
